toolID: 269
kickFlag: false
banFlag: true
shoutFlag: true

# set to true for MCBans global bans. Be sure to follow their
# guidelines:
# http://wiki.mcbans.com/display/MCBans/Honeypot+Guidelines
globalBan: false

banLog: true
banLogLocation: true
logPath: plugins/Honeypot/honeypot.log

honeypotKickBanSender: '[Honeypot]'
honeypotBanReason: Destroyed honeypot block.
honeypotKickMessage: '[Honeypot] You have been caught destroying a honeypot block.'

# valid types are:
#   any - this will find any ban plugin Honyepot knows about and use it.
#     This is the default and you generally shouldn't ever have to change
#     it, but there are some other options if you want to force this
#     setting (such as the custom type below).
#   custom - this uses the custom commands below. The custom commands are
#     ONLY used when this type is set, they are not used for the ANY type.
#   mcbans - this forces Honeypot to use MCBans, if found
#   vanilla - this will force Honeypot to use vanilla MC ban
#   [etc] - there are a few other ban systems that Honeypot supports
#     directly, they are named after the plugin itself, so just use the
#     plugin name. If it can't find it, Honeypot falls back to Vanilla.
banSystem: any

# you can define a custom command to be run for a ban - 'banSystem' type
# must be set to custom!
customBanCommand: ban %player% %reason%
# you can define a custom command to be run for a kick - 'banSystem' type
# must be set to custom!
customKickCommand: kick %player% %reason%


# can be used in lieu of "offensePoints", is a simpler concept.
# Basically counts each block break as one infraction so, for
# example, you can require that 3 honeypot blocks must be broken
# before action is taken.
#offenseCount: 0

# how may offense points until they are banned
#offensePoints: 3

# ability to make some blocks worth more or less points. Helpful
# if you're honeypotting a region that is a honeypot statue,
# for example, so you could ignore dirt/snow blocks, etc.
# This example makes iron/gold/diamond blocks worth 3 points
# and grass,snow and ice blocks worth 0
#offensePointMap:
#  "56": 3
#  "41": 3
#  "42": 3
#  "2": 0
#  "78": 0
#  "79": 0

# This defines which permission system is used. Vault and WEPIF
# (WEPIF is built into WorldEdit) are preferred, they both provide
# a nice interface to all other permission systems. If you don't have
# or don't want to use either of those, there is some native support
# for a few other permission systems that you can use. These are
# checked in the order they are listed for existence, and the
# first one to match is used.
permissions:
  - vault
  - wepif
  - pex
  - perm2-compat
  - superperms
  - ops
