name: ${project.name}
main: com.argo.bukkit.honeypot.Honeypot
url: ${project.url}
version: ${project.version}
author: Argomirr,morganm,dog.big
softdepend: [MCBans, WorldEdit]
commands:
 honeypot:
  description: Enables Op's to create honeypots by right clicking a block with a wooden axe.
  usage: /<command>
  aliases: [hp]
